### PR TITLE
added missing rule check for static world length score

### PR DESCRIPTION
**Pull request by Quix0r**
Another rule testing method, needed by ruleIsMet (see there), sorry to miss it in previous PR.

### CODE REVIEW

**Comment by Quix0r** [comment]
Ah, please also run `grunt concat uglify`.

**Comment by Quix0r** [comment]
Same error message what travis says is also here. :-(

**Comment by ablanco** [comment]
I forgot about minifying and bundling in the last release ^_^U
I'll release it again, this time properly.

**Comment by Quix0r** [comment]
Thank you for merging it in. :-)

**Comment by Quix0r** [comment]
But strange that travis shows errors ...

**Comment by ablanco** [comment]
Travis was showing errors because there was a new version of JSLint and some rules had changed. I've fixed the JSLint version now, I'm not willing to modify the code to pass the new version.

**Pull request merged**
