### PR TITLE
Update methods.js

### PR DESCRIPTION
**Pull request by glensc**
fix "paste" event name. refs 6bf68d0

### CODE REVIEW

**Comment by ablanco** [comment]
Thanks for your contribution!

**Comment by ablanco** [comment]
Humm, there is a problem with this. The paste event is firing before the content is actually present in the input, so it need to be reworked. I've created an issue to remind me to do it https://github.com/ablanco/jquery.pwstrength.bootstrap/issues/75

**Comment by glensc** [comment]
well. i found that only `keyup` event is neccessary, i.e the `change` and `paste` do get fired, but they are always accompanied with `keyup` event. but yea, i pasted with `ctrl`+`v`, pasting with mouse likely does not file `onkeyup`, and i tested with chrome only.

**Comment by ablanco** [comment]
Yes, the paste event if for pasting with the mouse. That's when the keyup does not fire.

**Pull request merged**
